### ISSUE TITLE
Powerfactory 2023 support

### ISSUE THREAD

**Issue by matbkri** [Energinet-AIG/PP-MTB#18]
Testing with PF 2023 preview has shown issues with results export.

**Comment by CVLenerginet** [comment]
I've tested multiple times throughout the day, running the script in the final release of PF 2023 without any crashes. Prevously, PF 2023 Preview version would crash nearly every time when exporting. The issue seems to be obsolete with the final release of PF 2023 and I will close it.

If any future problems are found, a new issue will be made for the specific problem.
